import argparse
import os
import datetime
import sys
from rocrate.rocrate import ROCrate
from rocrate.model.contextentity import ContextEntity

# Import your extractor modules to use their validation logic
import Extractor_BeadStudio
import Extractor_Thermal_Report
import Extractor_FMGeneration
import Extractor_IlluminaSampleSheet
import Extractor_FMAutoTilt
import Extractor_Nanopore    

def generate_folder_rocrate(input_folder):
    crate = ROCrate()

    # ---  Add properties to the Root Entity ---
    crate.root_dataset["name"] = "LAGE Experimental Raw Dataset"
    crate.root_dataset["description"] ="Raw experimental data files generated by LAGE lab instruments."
    crate.root_dataset["about"] = ("Descriptor for raw data files generated by LAGE lab instruments." 
                                   "This crate contains the original files as they were exported from the instruments, without any modifications or processing."
                                    "The metadata describes the context of the data generation, including the lab, the research institute, and the software used for processing.")
    crate.root_dataset["license"] = "https://opensource.org/licenses/MIT"
    crate.root_dataset["keywords"] = ["LAGE", "LADE"]
    crate.root_dataset["datePublished"] = datetime.datetime.now().date().isoformat()

    # --- Organizations ---
    area_science_park = crate.add(
        ContextEntity(crate, "#area-science-park", properties={
            "@type": "Organization",
            "name": "Area Science Park",
            "url": "https://www.areasciencepark.it/en/"
        })
    )

    rit = crate.add(
        ContextEntity(crate, "#rit", properties={
            "@type": "Organization",
            "name": "Research and Technology Institute (RIT)",
            "parentOrganization": {"@id": area_science_park.id}
        })
    )

    lade = crate.add(
        ContextEntity(crate, "#lade", properties={
            "@type": "Organization",
            "name": "Laboratory of Data Engineering (LADE)",
            "url": "https://www.areasciencepark.it/infrastrutture-di-ricerca/data-engineering-lade/",
            "parentOrganization": {"@id": rit.id}
        })
    )

    lage = crate.add(
        ContextEntity(crate, "#lage", properties={
            "@type": "Organization",
            "name": "Laboratory of Genomics and Epigenomics (LAGE)",
            "url": "https://www.areasciencepark.it/en/research-infrastructures/life-sciences/lage-genomics-and-epigenomics-laboratory/",
            "parentOrganization": {"@id": rit.id}
        })
    )

    # ---  Define the Processor (SoftwareApplication)  ---
    ro_crate_script = crate.add(ContextEntity(crate, "#folder-analyzer-script", properties={
        "@type": "SoftwareApplication",
        "name": "LAGE Folder Descriptor Generator",
        "description": "Script to generate RO-Crate descriptors for lab data folders recursively",
        "creator": {"@id": lade.id},
        "license": "https://opensource.org/licenses/MIT",
        "url": "https://github.com/RitAreaSciencePark/LAGE_Metadata_Extraction/blob/main/Src/Crate_Generator.py"

    }))

    # --- Instruments & Activities Definition ---
    # 1. Nanopore
    instrument_nano = crate.add(ContextEntity(crate, "#promethion-device", properties={
    "@type": "Device",
    "name": "Oxford Nanopore Promethion",
    "manufacturer": "Oxford Nanopore Technologies",
    "model": "Promethion 24/48",
    "url": "https://nanoporetech.com/products/promethion"
    }))
        # Define the sequencing activity associated with the Nanopore device
    run_nano = crate.add(ContextEntity(crate, "#nanopore-sequencing-activity", properties={
        "@type": "CreateAction",
        "name": "Nanopore Sequencing Run", 
        "instrument": {"@id": instrument_nano.id}
    }))

    # 2. Illumina iScan
    instrument_iscan = crate.add(ContextEntity(crate, "#iscan-device", properties={
    "@type": "Device",
    "name": "Illumina iScan",
    "manufacturer": "Illumina",
    "model": "iScan 24/48",
    "url": "https://www.illumina.com/systems/array-scanners/iscan.html"
    }))
        # Define the microarray scanning activity associated with the iScan device
    run_iscan = crate.add(ContextEntity(crate, "#iscan-microarray-activity", properties={
        "@type": "CreateAction", 
        "name": "Microarray Scanning", 
        "instrument": {"@id": instrument_iscan.id}
    }))

    # 3. Illumina NovaSeq
    instrument_novaseq = crate.add(ContextEntity(crate, "#novaseq-device", properties={
    "@type": "Device",
    "name": "Illumina NovaSeq",
    "manufacturer": "Illumina",
    "model": "NovaSeq 6000",
    "url": "https://www.illumina.com/systems/sequencing-platforms/novaseq.html"
    }))
        # Define the sequencing activity associated with the NovaSeq device
    run_novaseq = crate.add(ContextEntity(crate, "#illumina-sequencing-activity", properties={
        "@type": "CreateAction", 
        "name": "Illumina Sequencing Run", 
        "instrument": {"@id": instrument_novaseq.id}
    }))

    # --- MIME Type Mapping ---
    MIME_MAP = {
        '.csv': 'text/csv',
        '.txt': 'text/plain',
        '.md': 'text/markdown',
        '.json': 'application/json'
    }

    print(f" Starting validated scan of: {input_folder}")
    count = 0
    VALID_EXTENSIONS = ('.csv', '.txt', '.json', '.md')

    for root, dirs, files in os.walk(input_folder):
        for filename in files:
            ext = os.path.splitext(filename)[1].lower()
            if ext in VALID_EXTENSIONS:
                full_path = os.path.join(root, filename)
                rel_path = os.path.relpath(full_path, input_folder)
                
                # Default values
                assigned_run = None
                encoding = MIME_MAP.get(ext, 'application/octet-stream')

                # --- VALIDATION LOGIC ---
                # Check for Nanopore
                if Extractor_Nanopore.is_nanopore_file(full_path):
                    assigned_run = run_nano
                
                # Check for BeadStudio (iScan)
                elif Extractor_BeadStudio.is_beadstudio_file(full_path):
                    assigned_run = run_iscan
                
                # Check for Illumina Sample Sheets (NovaSeq)
                elif Extractor_IlluminaSampleSheet.is_illumina_samplesheet(full_path):
                    assigned_run = run_novaseq
                
                # Add other elif checks for Thermal Report, FMGeneration etc.

                # Build properties dictionary
                file_props = {
                    "name": filename,
                    "description": f"Validated {encoding} file",
                    "creator": {"@id": lage.id},
                    "encodingFormat": encoding,
                    "wasGeneratedBy": {"@id": ro_crate_script.id}
                }

                # Link to the specific Activity/Instrument if identified
                if assigned_run:
                    file_props["actionProcess"] = {"@id": assigned_run.id}
                    print(f" Identified & Added: {rel_path} -> {assigned_run.id}")
                else:
                    print(f" 📁 Added (Generic): {rel_path}")

                crate.add_file(full_path, dest_path=rel_path, properties=file_props)
                count += 1

    crate.write(input_folder)
    print(f"\n ✅ Success! Processed {count} files.")
    print(f"Generated Crate ('ro-crate-metadata.json') in: {input_folder}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate recursive RO-Crate with validation.")
    parser.add_argument("folder_path", help="The root folder to scan")
    args = parser.parse_args()
    
    if os.path.isdir(args.folder_path):
        generate_folder_rocrate(args.folder_path)
    else:
        print(f"❌ Error: {args.folder_path} is not a valid directory.")