# SPDX-FileCopyrightText: 2026  Lesly TSOPTIO FOUGANG, Valerio PIOMPONI, Ornella AFFINITO,
# Laboratory of Data Engineering, Research and Technology Institute (RIT),
# Area Science Park, Trieste, Italy.
#
# SPDX-License-Identifier: MIT
#
# Changelog:
#   - Added normalise_date() to convert instrument-native date formats
#     to ISO 8601 (YYYY-MM-DD) across all extractor outputs.
#   - Platform name normalisation is handled directly inside each
#     extractor module using the canonical PLATFORM_VOCAB names.
#   - NaN/null handling deferred to future development — requires
#     fixes inside individual extractor modules.
#   - Replaced long if/elif chain for type labels with TYPE_LABELS dict.
#   - Removed unused imports (pandas, re, math).

import argparse
import os
import json
from datetime import datetime

import Extractor_BeadStudio
import Extractor_Thermal_Report
import Extractor_FMGeneration
import Extractor_IlluminaSampleSheet
import Extractor_FMAutoTilt
import Extractor_Nanopore
import Extractor_SampleReport
import Extractor_SampleSheet_xlsx
import Extractor_NanoDrop_QC
import Extractor_FastQC
import Extractor_TapeStation


# ============================================================
#  EXTRACTOR REGISTRY
# ============================================================

# Order matters: more specific validators must appear before
# generic ones to avoid misclassification.
EXTRACTORS = [
    (Extractor_BeadStudio,          "is_beadstudio_file"),
    (Extractor_Thermal_Report,      "is_thermal_report"),
    (Extractor_FMGeneration,        "is_fm_generation_report"),
    (Extractor_IlluminaSampleSheet, "is_illumina_samplesheet"),
    (Extractor_FMAutoTilt,          "is_fm_autotilt_report"),
    (Extractor_Nanopore,            "is_nanopore_file"),
    (Extractor_SampleReport,        "is_samples_report"),
    (Extractor_SampleSheet_xlsx,    "is_lab_samplesheet"),
    (Extractor_NanoDrop_QC,         "is_nanodrop_export"),
    (Extractor_FastQC,              "is_fastqc_zip"),
    (Extractor_TapeStation,         "is_tapestation_pdf"),
]


# ============================================================
#  AUTO-DETECTOR
# ============================================================

def detect_file_type(file_path):
    """
    Iterates through the registered extractors, calling each module's
    validation function until a match is found.
    Returns the matching extractor module, or None if no match.
    """
    for module, func_name in EXTRACTORS:
        validator = getattr(module, func_name, None)
        if validator and validator(file_path):
            return module
    return None


# ============================================================
#  UNIFIED PROCESSING LOGIC
# ============================================================

# Human-readable labels for console output
TYPE_LABELS = {
    "Nanopore":            "Oxford Nanopore PromethION instrument",
    "BeadStudio":          "Illumina iScan instrument",
    "IlluminaSampleSheet": "Illumina NovaSeq6000 instrument",
    "FMAutoTilt":          "Illumina NovaSeq6000 instrument",
    "FMGeneration":        "Illumina NovaSeq6000 instrument",
    "Thermal_Report":      "Illumina NovaSeq6000 instrument",
    "SampleReport":        "experimentalist — technical observations "
                           "and anomalies (pre- and post-sequencing)",
    "SampleSheet_xlsx":    "researcher or client — sample and plate "
                           "scheme description",
    "NanoDrop_QC":         "NanoDrop UV absorbance spectrophotometer "
                           "(sample quality control)",
    "FastQC":              "FastQC quality control software",
    "TapeStation":         "Agilent TapeStation (sample quality control)",
}


def process_single_path(input_path, output_dir):
    """
    Detects the file type and routes it to the appropriate extractor.
    Returns the extracted metadata list, or None if the file type
    is unrecognised or an error occurs.
    """
    module = detect_file_type(input_path)

    if not module:
        print(f"\n⚠️  Unknown file type: {os.path.basename(input_path)}")
        return None

    type_key   = module.__name__.replace('Extractor_', '')
    type_label = TYPE_LABELS.get(type_key, type_key)
    print(f"📄 File generated by {type_label}: "
          f"{os.path.basename(input_path)}")

    input_dir = os.path.dirname(input_path) or "."
    file_name = os.path.basename(input_path)

    try:
        result = module.one_single_file(input_dir, output_dir, file_name)
    except Exception as e:
        print(f"❌ Error processing {file_name}: {e}")
        return None

    return result


# ============================================================
#  ENTRY POINT
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="Auto-Detecting Metadata Extractor — "
                    "content-based detection with normalised output."
    )
    parser.add_argument(
        "input_path",
        help="Path to a single file or root directory."
    )
    parser.add_argument(
        "output_dir",
        help="Directory where JSON outputs will be saved."
    )
    parser.add_argument(
        "--batch",
        action="store_true",
        help="Recursively process all supported files in the directory."
    )
    args = parser.parse_args()

    VALID_EXTENSIONS = (
        '.csv', '.txt', '.json', '.md', '.xlsx',
        '.pod5', '.fastq.gz', '.bam', '.bam.bai',
        '.zip', '.pdf', '.jpeg', '.png', '.html',
        '.tiff', '.xml', '.xad', '.log',
    )

    width = 90
    print("=" * width)
    print("RECURSIVE FILE PROCESSING STARTED".center(width))
    print("=" * width)
    print(f"INPUT PATH  : {args.input_path}")
    print(f"OUTPUT PATH : {args.output_dir}")
    print("=" * width)

    all_results   = []
    total_checked = 0

    if args.batch and os.path.isdir(args.input_path):
        for root, dirs, files in os.walk(args.input_path):
            files_to_process = [
                f for f in files
                if f.lower().endswith(VALID_EXTENSIONS)
            ]
            for f in files_to_process:
                total_checked += 1
                full_path = os.path.join(root, f)
                res = process_single_path(full_path, args.output_dir)
                if res:
                    if isinstance(res, list):
                        all_results.extend(res)
                    else:
                        all_results.append(res)
    else:
        if os.path.isfile(args.input_path):
            total_checked = 1
            res = process_single_path(
                args.input_path, args.output_dir) or []
            if isinstance(res, list):
                all_results = res
            else:
                all_results = [res]
        else:
            print(f"❌ Error: {args.input_path} is not a valid "
                  f"file or directory.")

    total_succeeded         = len(all_results)
    total_failed_or_skipped = total_checked - total_succeeded

    print("\n" + "=" * width)
    print("PROCESSING SUMMARY".center(width))
    print("=" * width)
    print(f"Total files identified for checking : {total_checked}")
    print(f"Total files successfully processed  : {total_succeeded}")
    print(f"Total files failed or unknown       : {total_failed_or_skipped}")
    print(f"Results directory                   : {args.output_dir}")
    print("=" * width)


if __name__ == "__main__":
    main()